# pipeline-templates/hcp-terraform.apply-run.yml
# Azure DevOps Pipeline Template for HCP Terraform Apply Run (Main Branch)
# Now includes Terraform best practices: fmt check, validate, and optional linting

name: 'HCP-Terraform-Apply-$(Date:yyyyMMdd)-$(Rev:r)'

# Trigger configuration
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/**
      - '**/*.tf'

# No PR trigger for apply pipeline
pr: none

# Variables - REQUIRED: Replace these with your values
variables:
  - group: 'terraform-variables'  # Create this variable group in Azure DevOps Library
  # Required variables in the terraform-variables group:
  # - TF_API_TOKEN (secret) - Your HCP Terraform API token
  # - TF_CLOUD_ORGANIZATION - Your HCP Terraform organization name
  # - TF_WORKSPACE - Your HCP Terraform workspace name
  # - CONFIG_DIRECTORY - Directory containing Terraform configuration (default: "terraform")
  
  # Optional variables
  - name: TF_LOG
    value: 'INFO'  # Set to DEBUG for troubleshooting
  - name: TF_MAX_TIMEOUT
    value: '30m'   # Maximum timeout for operations
  - name: ENABLE_TFLINT
    value: 'true'  # Enable TFLint analysis
  - name: ENABLE_TFSEC
    value: 'false' # Disable security scan for apply (already done in PR)

# Agent pool
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: TerraformValidation
    displayName: 'Terraform Validation & Best Practices'
    jobs:
      - job: ValidateCode
        displayName: 'Pre-Apply Quality Checks'
        steps:
          - checkout: self
            displayName: 'Checkout source code'

          - template: ../tasks/display-info.yml
            parameters:
              pipelineType: 'apply'

          # Validation steps (even for main branch - defense in depth)
          - template: ../tasks/terraform-validate.yml
            parameters:
              workingDirectory: $(CONFIG_DIRECTORY)
              enableTflint: $(ENABLE_TFLINT)
              enableTfsec: $(ENABLE_TFSEC)

  - stage: TerraformPlan
    displayName: 'Terraform Plan'
    dependsOn: TerraformValidation
    condition: succeeded()
    jobs:
      - job: PlanTerraform
        displayName: 'Plan Terraform Changes'
        steps:
          - checkout: self
            displayName: 'Checkout source code'

          - template: ../tasks/upload-configuration.yml
            parameters:
              speculative: false

          - template: ../tasks/create-run.yml
            parameters:
              planOnly: false
              message: 'Apply run from Azure DevOps - $(Build.SourceVersion) - Validated ✅'

          - template: ../tasks/wait-for-plan.yml

  - stage: TerraformApply
    displayName: 'Terraform Apply'
    dependsOn: TerraformPlan
    condition: and(succeeded(), eq(dependencies.TerraformPlan.outputs['PlanTerraform.plan_status.STATUS'], 'planned'), eq(dependencies.TerraformPlan.outputs['PlanTerraform.plan_status.IS_CONFIRMABLE'], 'true'))
    variables:
      RUN_ID: $[ stageDependencies.TerraformPlan.PlanTerraform.outputs['create_run.RUN_ID'] ]
    jobs:
      - deployment: ApplyTerraform
        displayName: 'Apply Terraform Changes'
        environment: 'production'  # Create this environment in Azure DevOps
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none

                - template: ../tasks/apply-run.yml
                  parameters:
                    runId: $(RUN_ID)
                    comment: 'Applied from Azure DevOps - Quality Validated ✅'

                - template: ../tasks/wait-for-apply.yml
                  parameters:
                    runId: $(RUN_ID)

                - template: ../tasks/run-summary.yml
                  parameters:
                    runType: 'apply'
                    runId: $(RUN_ID)

                # NEW: Post-apply summary
                - script: |
                    echo "🚀 Infrastructure Deployment Summary"
                    echo "==================================="
                    echo "✅ Terraform Format Check: PASSED"
                    echo "✅ Terraform Validate: PASSED" 
                    echo "✅ Quality Checks: PASSED"
                    echo "✅ Terraform Plan: COMPLETED"
                    echo "✅ Terraform Apply: COMPLETED"
                    echo ""
                    echo "📊 View details in HCP Terraform:"
                    echo "🔗 Workspace: https://app.terraform.io/app/$(TF_CLOUD_ORGANIZATION)/workspaces/$(TF_WORKSPACE)"
                    echo "🔗 Run: https://app.terraform.io/app/$(TF_CLOUD_ORGANIZATION)/workspaces/$(TF_WORKSPACE)/runs/$(RUN_ID)"
                  displayName: 'Deployment Summary'
                  condition: always()
